version: '3.4'

services:

  sqlserver:
    image: ${DOCKER_REGISTRY-}mcr.microsoft.com/mssql/server:2017-latest-ubuntu 
    hostname: 'sqlserver'  
    container_name: 'sqlserver'
    environment:  
      ACCEPT_EULA: Y  
      SA_PASSWORD: "Password123"     
    ports:  
      - '1433:1433'
    expose:
      - 1433
    volumes:  
      - /var/container_data/mysql:/var/lib/mysql mysql_image
    deploy:
      placement:
        constraints: [node.role == manager]
  
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    container_name: 'RabbitMq'
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
      - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config
    depends_on:
      - sqlserver

  monitor:
    image: ${DOCKER_REGISTRY-}monitor
    hostname: "monitor"
    container_name: 'HealtMonitor'
    ports:
      - "8091:80"
    build:
      context: .
      dockerfile: Services/Monitor/Monitor/Dockerfile
    depends_on:
      - sqlserver
      - rabbitmq

  eventstore:
    image: ${DOCKER_REGISTRY-}eventstore_api
    hostname: "eventstore"    
    ports:
      - "8070:80"
    build:
      context: .
      dockerfile: Services/EventStore/EventStore_Api/Dockerfile
    depends_on:
      - sqlserver
      - rabbitmq

  webapiocelot:
    image: ${DOCKER_REGISTRY-}webapi
    hostname: "webapiocelot"       
    ports:
      - "8090:80"
    build:
      context: .
      dockerfile: Api/WebApi/Dockerfile
    depends_on:
      - sqlserver
      - rabbitmq
      - eventstore

  kalendarapi:
    image: ${DOCKER_REGISTRY-}kalendar_api
    hostname: "kalendarapi"       
    ports:
      - "8086:80"
    build:
      context: .
      dockerfile: Services/Kalendar/Kalendar_Api/Dockerfile
    depends_on:
      - sqlserver
      - rabbitmq
      - eventstore

  udalostapi:
    image: ${DOCKER_REGISTRY-}udalost_api
    hostname: "udalostapi"       
    ports:
      - "8083:80"
    build:
      context: .
      dockerfile: Services/Udalost/Udalost_Api/Dockerfile
    depends_on:
      - sqlserver
      - rabbitmq
      - eventstore

  dochazkaapi:
    image: ${DOCKER_REGISTRY-}dochazka_api
    hostname: "dochazkaapi"       
    ports:
      - "8084:80"
    build:
      context: .
      dockerfile: Services/Dochazka/Dochazka_Api/Dockerfile
    depends_on:
      - sqlserver
      - rabbitmq
      - eventstore

  uzivatelapi:
    image: ${DOCKER_REGISTRY-}uzivatel_api
    hostname: "uzivatelapi"       
    ports:
      - "8085:80"
    build:
      context: .
      dockerfile: Services/Uzivatel/Uzivatel_Api/Dockerfile
    depends_on:
      - sqlserver
      - rabbitmq
      - eventstore

  kancelarweb:
    image: ${DOCKER_REGISTRY-}kancelarweb
    ports:
      - "85:80"
    build:
      context: .
      dockerfile: Gui/KancelarWeb/Dockerfile
    depends_on:
      - sqlserver
      - rabbitmq
      - eventstore







       

