version: '3.4'

services:

  sqlserver:
    image: ${DOCKER_REGISTRY-}mcr.microsoft.com/mssql/server:2017-latest-ubuntu 
    hostname: 'sqlserver'  
    container_name: 'sqlserver'
    environment:  
      ACCEPT_EULA: Y  
      SA_PASSWORD: "Password123"     
    ports:  
      - '1433:1433'
    expose:
      - 1433
    volumes:  
      - /var/container_data/mysql:/var/lib/mysql mysql_image
    deploy:
      placement:
        constraints: [node.role == manager]
 
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    container_name: 'RabbitMq'
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
      - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config

  kancelarweb:
    image: ${DOCKER_REGISTRY-}kancelarweb
    ports:
      - "85:80"
    build:
      context: .
      dockerfile: Gui/KancelarWeb/Dockerfile

#  webapi:
#    image: ${DOCKER_REGISTRY-}web_api
#    hostname: "webapi"       
#    ports:
#      - "8080:80"
#    build:
#      context: .
#      dockerfile: Api/Web_Api/Dockerfile
#    depends_on:
#      - sqlserver
#      - rabbitmq

  webapiocelot:
    image: ${DOCKER_REGISTRY-}webapi
    hostname: "webapiocelot"       
    ports:
      - "8090:80"
    build:
      context: .
      dockerfile: Api/WebApi/Dockerfile
    depends_on:
      - sqlserver

  dochazkaservice:
    image: ${DOCKER_REGISTRY-}dochazka_service
    hostname: "dochazkaservice"    
    ports:
      - "8081:80"
    build:
      context: .
      dockerfile: Services/Dochazka/Dochazka_Service/Dockerfile
    depends_on:
      - sqlserver
      - rabbitmq

  udalostservice:
    image: ${DOCKER_REGISTRY-}udalost_service
    hostname: "udalostservice"    
    ports:
      - "8082:80"
    build:
      context: .
      dockerfile: Services/Udalost/Udalost_Service/Dockerfile
    depends_on:
      - sqlserver
      - rabbitmq

  udalostapi:
    image: ${DOCKER_REGISTRY-}udalost_api
    hostname: "udalostapi"       
    ports:
      - "8083:80"
    build:
      context: .
      dockerfile: Services/Udalost/Udalost_Api/Dockerfile
    depends_on:
      - sqlserver
      - rabbitmq

  dochazkaapi:
    image: ${DOCKER_REGISTRY-}dochazka_api
    hostname: "dochazkaapi"       
    ports:
      - "8084:80"
    build:
      context: .
      dockerfile: Services/Dochazka/Dochazka_Api/Dockerfile
    depends_on:
      - sqlserver
      - rabbitmq




       

