version: '3.4'

services:

  sqlserver:
    image: ${DOCKER_REGISTRY-}mcr.microsoft.com/mssql/server:2017-latest-ubuntu 
    hostname: 'sqlserver'  
    container_name: 'sqlserver'
    environment:  
      ACCEPT_EULA: Y  
      SA_PASSWORD: "Password123"     
    ports:  
      - '1433:1433'
    expose:
      - 1433
    volumes:  
      - /var/container_data/mysql:/var/lib/mysql mysql_image
    deploy:
      placement:
        constraints: [node.role == manager]
  
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    container_name: 'RabbitMq'
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
      - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config
    depends_on:
      - sqlserver

  gateway:
    image: ${DOCKER_REGISTRY-}webapi
    hostname: "gateway"       
    ports:
      - "8050:80"
    build:
      context: .
      dockerfile: Api/WebApi/Dockerfile
    depends_on:
      - sqlserver
      - rabbitmq
  monitor:
    image: ${DOCKER_REGISTRY-}monitor
    hostname: "monitor"
    container_name: 'HealtMonitor'
    ports:
      - "8051:80"
    build:
      context: .
      dockerfile: Services/Monitor/Monitor/Dockerfile
    depends_on:
      - sqlserver
      - rabbitmq

  template:
    image: ${DOCKER_REGISTRY-}template
    hostname: "template"
    container_name: 'Template'
    ports:
      - "8052:80"
    build:
      context: .
      dockerfile: Services/Template/Template/Dockerfile
    depends_on:
      - sqlserver
      - rabbitmq
      - eventstore
      - monitor

  importapi:
    image: ${DOCKER_REGISTRY-}import_api
    hostname: "importapi"
    container_name: 'importapi'
    ports:
      - "8053:80"
    build:
      context: .
      dockerfile: Services/Import/Import_Api/Dockerfile



  eventstore:
    image: ${DOCKER_REGISTRY-}eventstore
    hostname: "eventstore"    
    ports:
      - "8054:80"
    build:
      context: .
      dockerfile: Services/EventStore/EventStore/Dockerfile
    depends_on:
      - sqlserver
      - rabbitmq


  kalendarapi:
    image: ${DOCKER_REGISTRY-}kalendar_api
    hostname: "kalendarapi"       
    ports:
      - "8055:80"
    build:
      context: .
      dockerfile: Services/Kalendar/Kalendar_Api/Dockerfile
    depends_on:
      - sqlserver
      - rabbitmq

  udalostapi:
    image: ${DOCKER_REGISTRY-}udalost_api
    hostname: "udalostapi"       
    ports:
      - "8056:80"
    build:
      context: .
      dockerfile: Services/Udalost/Udalost_Api/Dockerfile
    depends_on:
      - sqlserver
      - rabbitmq

  dochazkaapi:
    image: ${DOCKER_REGISTRY-}dochazka_api
    hostname: "dochazkaapi"       
    ports:
      - "8057:80"
    build:
      context: .
      dockerfile: Services/Dochazka/Dochazka_Api/Dockerfile
    depends_on:
      - sqlserver
      - rabbitmq

  uzivatelapi:
    image: ${DOCKER_REGISTRY-}uzivatel_api
    hostname: "uzivatelapi"       
    ports:
      - "8058:80"
    build:
      context: .
      dockerfile: Services/Uzivatel/Uzivatel_Api/Dockerfile


  pritomnostapi:
    image: ${DOCKER_REGISTRY-}pritomnost_api
    hostname: "pritomnostapi"       
    ports:
      - "8059:80"
    build:
      context: .
      dockerfile: Services/Pritomnost/Pritomnost_Api/Dockerfile
    depends_on:
      - sqlserver
      - rabbitmq

  kancelarweb:
    image: ${DOCKER_REGISTRY-}kancelarweb
    ports:
      - "85:80"
    build:
      context: .
      dockerfile: Gui/KancelarWeb/Dockerfile
    depends_on:
      - sqlserver
      - rabbitmq







       

