version: '3.4'

services:

  sqlserver:
    image: ${DOCKER_REGISTRY-}mcr.microsoft.com/mssql/server:2017-latest-ubuntu 
    hostname: 'sqlserver'  
    restart: always
    container_name: 'sqlserver'
    environment:  
      ACCEPT_EULA: Y  
      SA_PASSWORD: "Password123"     
    ports:  
      - '1433:1433'
    expose:
      - 1433
    volumes:  
      - /var/container_data/mysql:/var/lib/mysql mysql_image
      
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    restart: always
    container_name: 'RabbitMq'
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
      - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config

  gateway:
    image: ${DOCKER_REGISTRY-}webapi
    hostname: "gateway"  
    restart: always
    ports:
      - "8030:80"
    build:
      context: .
      dockerfile: Api/WebApi/Dockerfile

  monitor:
    image: ${DOCKER_REGISTRY-}monitor
    hostname: "monitor"
    restart: always
    container_name: 'HealtMonitor'
    ports:
      - "8031:80"
    build:
      context: .
      dockerfile: Services/Monitor/Monitor/Dockerfile

  template:
    image: ${DOCKER_REGISTRY-}template
    hostname: "template"
    restart: always
    container_name: 'Template'
    ports:
      - "8032:80"
    build:
      context: .
      dockerfile: Services/Template/Template/Dockerfile

  transferapi:
    image: ${DOCKER_REGISTRY-}transfer_api
    hostname: "transferapi"
    restart: always
    ports:
      - "8033:80"
    build:
      context: .
      dockerfile: Services/Transfer/Transfer_Api/Dockerfile

  eventstore:
    image: ${DOCKER_REGISTRY-}eventstore
    hostname: "eventstore"  
    restart: always
    ports:
      - "8034:80"
    build:
      context: .
      dockerfile: Services/EventStore/EventStore/Dockerfile

  kalendarapi:
    image: ${DOCKER_REGISTRY-}kalendar_api
    hostname: "kalendarapi" 
    restart: always
    ports:
      - "8035:80"
    build:
      context: .
      dockerfile: Services/Kalendar/Kalendar_Api/Dockerfile

  udalostapi:
    image: ${DOCKER_REGISTRY-}udalost_api
    hostname: "udalostapi"  
    restart: always
    ports:
      - "8036:80"
    build:
      context: .
      dockerfile: Services/Udalost/Udalost_Api/Dockerfile

  dochazkaapi:
    image: ${DOCKER_REGISTRY-}dochazka_api
    hostname: "dochazkaapi"
    restart: always
    ports:
      - "8037:80"
    build:
      context: .
      dockerfile: Services/Dochazka/Dochazka_Api/Dockerfile

  uzivatelapi:
    image: ${DOCKER_REGISTRY-}uzivatel_api
    hostname: "uzivatelapi" 
    restart: always
    ports:
      - "8038:80"
    build:
      context: .
      dockerfile: Services/Uzivatel/Uzivatel_Api/Dockerfile



  kancelarweb:
    image: ${DOCKER_REGISTRY-}kancelarweb
    ports:
      - "85:80"
    build:
      context: .
      dockerfile: Gui/KancelarWeb/Dockerfile








       

